### PR TITLE
Feature/Structure Dragons Redux

### LINKED ISSUE #40: Team3 [1pt] Create basic structure for Dragons - Setup
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

### PR DESCRIPTION
**Pull request by adel-gu**
# In this PR I accomplished the points below:

- Create a Redux directory, and add a dragon sub-directory with the `dragonsSlice.js` file in it.
- Added a `configureStore.js` file inside the Redux directory, Then I prepared the store for combining the reducers.
- For the `Navbar` component I change its `CSS fixed position` to nothing to fix the `Views` layouts.

### CODE REVIEW

**Review by GoddessNgozi — CHANGES_REQUESTED** [review]
Hi @adel-gu  

Good job so far!
You still need to work on some issues but you are almost there!
There are a few bugs 🐛  that you still need to work 🛠️  on to go to the next project ⏭️, but you are almost there! 🏃🏾 

## Highlights 
 - [x] Correct GitHub Flow 👍🏾 
 - [x] Good commit history 🥇 
 - [x] Good PR title/description 💯 
 - [x] All linters passed 🥇 

## Required Changes ♻️
Screenshot 2022-11-15 at 12 23 34

Hint: Change the Redux directory name to redux with a small "r". Also check my comment down below.

Cheers and Happy coding!👏👏👏

------

**Comment by GoddessNgozi** [comment]
Dragons basic structure:
Screenshot 2022-11-15 at 12 24 22

Please structure the dragons page according to the project requirement.

**Comment by adel-gu** [comment]
**Hi @GoddessNgozi** 

Thank you very much 👏👏👏 for the clarification, actually, it does make sense now 👍.

**Review by GoddessNgozi — APPROVED** [review]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image

Cheers and Happy coding!👏👏👏

**Pull request merged**
